### ISSUE TITLE
verwarrend label child(ren)

### ISSUE THREAD

**Issue by coret** [CBG-Centrum-voor-familiegeschiedenis/PiCo#17]
https://github.com/CBG-Centrum-voor-familiegeschiedenis/PiCo/blob/8e0b3675aa513730783fd2fc66661a22f1b989e9/pico.ttl#L688
De property `children` heeft als label `child`, dit is wat verwarrend, te meer omdat alle andere rdfs:labels overeenkomen met de property name.

**Comment by pwoltjer** [comment]
Hoi Bob,
Er zijn een paar gevallen waarin het label in PiCo afwijkt van de naam van de klasse of property in de oorspronkelijke ontologie:

- pnv:Name --> PersonName
- pnv:givenName --> givenName (pnv)
- sdo:givenName --> givenName (schema)
- sdo:ImageObject --> Scan
- sdo:ArchiveComponent --> Source
- sdo:children --> sdo:child

Bij givenName heb ik dat natuurlijk gedaan om onderscheid te maken tussen de twee eigenschappen met dezelfde naam. En pnv:Name wou ik duidelijk onderscheiden van sdo:name, die niet alleen gebruikt voor een Person, maar ook voor een Source.

Bij ImageObject en ArchiveComponent vind ik de labels Scan en Source beter de lading dekking in de context van PiCo. We praten altijd over een Persoonsvermelding die voorkomt op een Bron. En van die Bron hebben we (mogelijk) een Scan. Het leek me daarom goed om die termen ook te gebruiken in het model. Het maakt de PiCo schema's ook beter leesbaar (in mijn ogen): https://personsincontext.org/model/#Model-overview.

Dat je valt over sdo:children kan ik wel begrijpen. Persoonlijk begrijp ik niet zo goed waarom schema.org hier heeft gekozen voor meervoud. Bij parent en sibling doen ze dat immers ook niet. Maar je hebt ook gelijk dat PiCo niet hoeft te proberen om het "beter te weten".

Mijn voorstel: we wijzigen het label van sdo:child naar sdo:children. De andere labels laten we zo. Akkoord?

**Comment by coret** [comment]
Mee eens.

Wellicht wel  `For Scans of Sources: a link to the scan of the Source at the holding archive. Preferably a link to a IIIF manifest.` als scopeNote bij Scan zetten in plaats van Source (en het deel For..archive. weglaten).

**Comment by pwoltjer** [comment]
Done! Zeer bedankt voor je feedback, Bob.
