### ISSUE TITLE
from / to # namespace/

### ISSUE THREAD

**Issue by pwoltjer** [CBG-Centrum-voor-familiegeschiedenis/PiCo#23]
Hallo PiCo gebruikers / beheerders,

Vóór we overgaan naar de publicatie van PiCo 1.0, wil ik één heel fundamenteel punt aankaarten:

Op dit moment gebruiken we een slash namespace, bijvoorbeeld: https://personsincontext.org/model/PersonObservation. (met een "/" achter de base URL ...model/PersonObservation)

Dit blijkt lastig in te richten op onze hosting omgeving. Op mijn eigen servertje had ik het eerder wel aan de praat, maar in de echte wereld is het allemaal niet zo makkelijk.

Om complicaties nu en in de toekomst te voorkomen, zou ik graag overgaan naar een # namespace, dus: https://personsincontext.org/model#PersonObservation (met een # achter de base URL ...model#PersonObservation)

Een hele kleine verandering, maar wel met een grote impact: de pico prefix van alle bestaande datasets moeten aangepast worden, omdat de URI van alle PiCo klassen en properties wijzigt. 

Volgens mij hebben de volgende partijen op dit moment een dataset in PiCo gemaakt, of zijn daar mee bezig:
* WO2Net
* IISG / HDBSC
* Bob Coret
* HUA 

Hebben jullie bezwaar tegen deze wijziging en de impact die dat heeft op jullie datasets? Ik hoor graag even of je wel/geen bezwaren hebt.

**Comment by RJMourits** [comment]
Dag allen, er zijn nog geen queries of applicaties geschreven op de beschikbare databases in PiCo, dus voor het IISG geeft het geen complicaties.

**Comment by companje** [comment]
Geen probleem voor HUA.

Groet!
Rick



Op do 26 sep 2024 om 16:03 schreef RJMourits ***@***.***>:

**Comment by coret** [comment]
Geen probleem!

**Comment by mschorsij** [comment]
Hier ook makkelijk aan te passen
