### ISSUE TITLE
redefine persons in context prefix to: piex

### ISSUE THREAD

**Issue by rlzijdeman** [CBG-Centrum-voor-familiegeschiedenis/PiCo#28]
Hi,

The wonderful Persons in Context vocabulary is now in documentation shortened to 'PiCo'. For two reasons this is not great. The first is, that 'PiCo' seems very similar to the Records in Context vocabulary (RiCO), yet has neither in design nor organisation any link to the RiCO endeavour, other than that both our doing great work! The second and very pressing reason is that there already is a [linked data](https://www.cochranelibrary.com/about-cochrane-pico-linked-data) project utilising 'their' [PiCO](https://www.cochranelibrary.com/about-pico#:~:text=PICO%20stands%20for%20four%20different,condition%20or%20disease%20of%20interest%3F)  to study data around patients and overlaps with the same domain as Persons in Context. 

To make sure that Persons in Context will be adapted throughout the SSH domain, I therefore have a very small request, which is not to change the name (Persons in Context), but only to change the 'shortened version' of the name to 'piex' (pronounced as 'peaks' in EN-GB). Persons in Context is still a young product and having the name land well, is very important to its uptake. 

Surely, there is some work required to adjust examples and such, but that work is limited and can be fixed in the next weeks. Not taking action, will cause confusion in years to come and may even hinder the uptake of Persons in Context. I therefore hope you will decide to use 'piex' as abbreviated name and prefix or a similar alternative.

**Comment by pwoltjer** [comment]
Good point, Richard. We sure want to avoid confusion with the Cochrane Library.  (Cochrane Reviews is my favorite go-to site for any questions about medical science. These guys do great work.)

piex sound like a good alternative namespace prefix. I'm not sure if it will replace PiCo in everyday speak. But that may not be a problem? People talk about Schema even when they use the sdo prefix. 

Let's discuss this on december 3.

**Comment by pwoltjer** [comment]
As discussed during the last PiCo maintenance group meeting:
* The name Persons in Context and it's abbreviation PiCo are already well established in the Dutch cultural heritage sector.
* We will change the preferred namespace prefix from pico to picom (from: pico model). 
* The PiCo documentation will keep using the abbreviation "PiCo" to refer to Persons in Context.
* All examples on GitHub en personsincontext.org will be (already are) updated to use the picom prefix.
